-- Script para adicionar dados mock à tabela normas
-- Desabilitar RLS temporariamente
ALTER TABLE normas DISABLE ROW LEVEL SECURITY;

-- Inserir dados mock de normas
INSERT INTO normas (
  id,
  codigo,
  titulo,
  descricao,
  categoria,
  subcategoria,
  organismo,
  versao,
  data_publicacao,
  data_entrada_vigor,
  status,
  escopo,
  aplicabilidade,
  requisitos_principais,
  metodos_ensaio,
  limites_aceitacao,
  documentos_relacionados,
  documentos_anexos,
  observacoes,
  tags,
  prioridade,
  ultima_atualizacao,
  criado_em,
  atualizado_em
) VALUES 
-- Normas de Construção Civil
(
  gen_random_uuid(),
  'EN 1992-1-1',
  'Eurocódigo 2: Projeto de estruturas de betão - Parte 1-1: Regras gerais e regras para edifícios',
  'Norma europeia para projeto de estruturas de betão armado e pré-esforçado',
  'CONSTRUCAO_CIVIL',
  'Estruturas',
  'CEN',
  '2004',
  '2004-04-01',
  '2004-10-01',
  'ATIVA',
  'Estruturas de betão armado e pré-esforçado',
  ARRAY['Edifícios', 'Pontes', 'Estruturas industriais'],
  ARRAY['Resistência à compressão mínima', 'Cobrimento mínimo', 'Armadura mínima'],
  ARRAY['Ensaio de compressão', 'Ensaio de tração', 'Ensaio de flexão'],
  '{"resistencia_compressao": "C25/30", "cobrimento_minimo": "25mm"}',
  ARRAY['EN 1990', 'EN 1991'],
  NULL,
  'Norma fundamental para projeto de estruturas de betão',
  ARRAY['betão', 'estruturas', 'eurocódigo'],
  'CRITICA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'EN 1993-1-1',
  'Eurocódigo 3: Projeto de estruturas de aço - Parte 1-1: Regras gerais e regras para edifícios',
  'Norma europeia para projeto de estruturas de aço',
  'CONSTRUCAO_CIVIL',
  'Estruturas',
  'CEN',
  '2005',
  '2005-03-01',
  '2005-09-01',
  'ATIVA',
  'Estruturas de aço',
  ARRAY['Edifícios', 'Pontes', 'Estruturas industriais'],
  ARRAY['Resistência à tração', 'Estabilidade', 'Ligações'],
  ARRAY['Ensaio de tração', 'Ensaio de impacto', 'Ensaio de dureza'],
  '{"resistencia_tracao": "S235", "modulo_elasticidade": "210000MPa"}',
  ARRAY['EN 1990', 'EN 1991'],
  NULL,
  'Norma fundamental para projeto de estruturas de aço',
  ARRAY['aço', 'estruturas', 'eurocódigo'],
  'CRITICA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),

-- Normas Ferroviárias
(
  gen_random_uuid(),
  'EN 13848-1',
  'Via férrea - Qualidade geométrica da via - Parte 1: Características da qualidade geométrica',
  'Norma para controlo da qualidade geométrica da via férrea',
  'FERROVIARIA',
  'Via Férrea',
  'CEN',
  '2019',
  '2019-06-01',
  '2019-12-01',
  'ATIVA',
  'Via férrea convencional',
  ARRAY['Linhas principais', 'Linhas secundárias', 'Manutenção'],
  ARRAY['Alinhamento', 'Nivelamento', 'Bitola'],
  ARRAY['Medição de alinhamento', 'Medição de nivelamento', 'Medição de bitola'],
  '{"desvio_alinhamento": "±10mm", "desvio_nivelamento": "±15mm"}',
  ARRAY['EN 13848-2', 'EN 13848-3'],
  NULL,
  'Norma essencial para manutenção da via férrea',
  ARRAY['via férrea', 'geometria', 'qualidade'],
  'ALTA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'EN 50126-1',
  'Aplicação de técnicas de fiabilidade, disponibilidade, manutenibilidade e segurança (FRACAS) - Parte 1: Processo básico e terminologia',
  'Norma para gestão de fiabilidade em sistemas ferroviários',
  'FERROVIARIA',
  'Segurança Ferroviária',
  'CENELEC',
  '2017',
  '2017-09-01',
  '2018-03-01',
  'ATIVA',
  'Sistemas ferroviários',
  ARRAY['Infraestrutura', 'Material circulante', 'Sinalização'],
  ARRAY['Análise de riscos', 'Gestão de fiabilidade', 'Processo de segurança'],
  ARRAY['Análise FMEA', 'Análise de árvore de falhas', 'Análise de riscos'],
  '{"disponibilidade_minima": "99.5%", "tempo_medio_falha": "10000h"}',
  ARRAY['EN 50126-2', 'EN 50128'],
  NULL,
  'Norma fundamental para segurança ferroviária',
  ARRAY['fiabilidade', 'segurança', 'ferroviário'],
  'CRITICA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),

-- Normas de Betão Estrutural
(
  gen_random_uuid(),
  'EN 206',
  'Betão - Especificação, desempenho, produção e conformidade',
  'Norma para especificação e controlo de qualidade do betão',
  'BETAO_ESTRUTURAL',
  'Composição e Propriedades',
  'CEN',
  '2013',
  '2013-12-01',
  '2014-06-01',
  'ATIVA',
  'Betão estrutural',
  ARRAY['Estruturas', 'Fundações', 'Pavimentos'],
  ARRAY['Resistência à compressão', 'Consistência', 'Durabilidade'],
  ARRAY['Ensaio de consistência', 'Ensaio de resistência', 'Ensaio de durabilidade'],
  '{"resistencia_compressao": "C25/30", "consistencia": "S3"}',
  ARRAY['EN 1992-1-1', 'EN 12350'],
  NULL,
  'Norma fundamental para controlo de qualidade do betão',
  ARRAY['betão', 'qualidade', 'estrutural'],
  'CRITICA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'EN 12350',
  'Ensaio de betão fresco - Parte 1: Determinação da consistência',
  'Norma para ensaios de betão fresco',
  'BETAO_ESTRUTURAL',
  'Ensaios e Controlo',
  'CEN',
  '2019',
  '2019-03-01',
  '2019-09-01',
  'ATIVA',
  'Betão fresco',
  ARRAY['Produção', 'Transporte', 'Aplicação'],
  ARRAY['Consistência', 'Trabalhabilidade', 'Tempo de pega'],
  ARRAY['Ensaio de abatimento', 'Ensaio de espalhamento', 'Ensaio de tempo de pega'],
  '{"abatimento_minimo": "50mm", "abatimento_maximo": "200mm"}',
  ARRAY['EN 206', 'EN 12390'],
  NULL,
  'Norma para controlo de qualidade do betão fresco',
  ARRAY['betão', 'ensaio', 'fresco'],
  'ALTA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),

-- Normas de Solos e Fundações
(
  gen_random_uuid(),
  'EN 1997-1',
  'Eurocódigo 7: Projeto geotécnico - Parte 1: Regras gerais',
  'Norma para projeto geotécnico',
  'SOLOS_FUNDACOES',
  'Fundações',
  'CEN',
  '2004',
  '2004-04-01',
  '2004-10-01',
  'ATIVA',
  'Projeto geotécnico',
  ARRAY['Fundações', 'Muros de suporte', 'Escavações'],
  ARRAY['Capacidade de carga', 'Estabilidade', 'Deformações'],
  ARRAY['Ensaio de penetração', 'Ensaio de cisalhamento', 'Ensaio de compressão'],
  '{"fator_seguranca": "3.0", "deformacao_maxima": "25mm"}',
  ARRAY['EN 1990', 'EN 1997-2'],
  NULL,
  'Norma fundamental para projeto geotécnico',
  ARRAY['geotécnico', 'fundações', 'eurocódigo'],
  'CRITICA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00Z'
),
(
  gen_random_uuid(),
  'EN ISO 14688-1',
  'Identificação e classificação de solos - Parte 1: Identificação e descrição',
  'Norma para identificação e classificação de solos',
  'SOLOS_FUNDACOES',
  'Identificação de Solos',
  'ISO',
  '2018',
  '2018-06-01',
  '2018-12-01',
  'ATIVA',
  'Identificação de solos',
  ARRAY['Investigação geotécnica', 'Classificação', 'Descrição'],
  ARRAY['Granulometria', 'Plasticidade', 'Consistência'],
  ARRAY['Análise granulométrica', 'Ensaio de plasticidade', 'Ensaio de consistência'],
  '{"tamanho_maximo": "63mm", "limite_liquidez": "LL"}',
  ARRAY['EN ISO 14688-2', 'EN ISO 14689'],
  NULL,
  'Norma para identificação e classificação de solos',
  ARRAY['solos', 'classificação', 'identificação'],
  'ALTA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),

-- Normas de Aços e Armaduras
(
  gen_random_uuid(),
  'EN 10080',
  'Aços para armaduras de betão - Aços soldáveis para armaduras de betão - Produtos longos',
  'Norma para aços de armadura',
  'ACOS_ARMADURA',
  'Aços de Armadura',
  'CEN',
  '2005',
  '2005-09-01',
  '2006-03-01',
  'ATIVA',
  'Aços de armadura',
  ARRAY['Armaduras', 'Estruturas', 'Fundações'],
  ARRAY['Resistência à tração', 'Ductilidade', 'Soldabilidade'],
  ARRAY['Ensaio de tração', 'Ensaio de dobramento', 'Ensaio de soldabilidade'],
  '{"resistencia_tracao": "500MPa", "alongamento": "5%"}',
  ARRAY['EN 1992-1-1', 'EN 10025'],
  NULL,
  'Norma para aços de armadura',
  ARRAY['aços', 'armadura', 'estrutural'],
  'CRITICA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'EN 10025-1',
  'Produtos laminados a quente de aços estruturais - Parte 1: Condições técnicas gerais de entrega',
  'Norma para aços estruturais',
  'ACOS_ARMADURA',
  'Aços Estruturais',
  'CEN',
  '2004',
  '2004-12-01',
  '2005-06-01',
  'ATIVA',
  'Aços estruturais',
  ARRAY['Estruturas', 'Construção', 'Indústria'],
  ARRAY['Resistência mecânica', 'Tenacidade', 'Soldabilidade'],
  ARRAY['Ensaio de tração', 'Ensaio de impacto', 'Ensaio de soldabilidade'],
  '{"resistencia_tracao": "S235", "temperatura_transicao": "-20°C"}',
  ARRAY['EN 1993-1-1', 'EN 10025-2'],
  NULL,
  'Norma para aços estruturais',
  ARRAY['aços', 'estrutural', 'laminado'],
  'ALTA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),

-- Normas de Materiais de Construção
(
  gen_random_uuid(),
  'EN 197-1',
  'Cimento - Parte 1: Composição, especificações e critérios de conformidade para cimentos comuns',
  'Norma para cimentos',
  'MATERIAIS_CONSTRUCAO',
  'Cimentos',
  'CEN',
  '2011',
  '2011-06-01',
  '2011-12-01',
  'ATIVA',
  'Cimentos comuns',
  ARRAY['Betão', 'Argamassas', 'Construção'],
  ARRAY['Resistência à compressão', 'Tempo de pega', 'Fineness'],
  ARRAY['Ensaio de resistência', 'Ensaio de tempo de pega', 'Ensaio de fineness'],
  '{"resistencia_28d": "42.5MPa", "tempo_pega_inicial": "45min"}',
  ARRAY['EN 196', 'EN 206'],
  NULL,
  'Norma fundamental para cimentos',
  ARRAY['cimento', 'construção', 'aglomerante'],
  'CRITICA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'EN 12620',
  'Agregados para betão',
  'Norma para agregados para betão',
  'MATERIAIS_CONSTRUCAO',
  'Agregados',
  'CEN',
  '2013',
  '2013-06-01',
  '2013-12-01',
  'ATIVA',
  'Agregados para betão',
  ARRAY['Betão', 'Argamassas', 'Construção'],
  ARRAY['Granulometria', 'Resistência', 'Durabilidade'],
  ARRAY['Análise granulométrica', 'Ensaio de resistência', 'Ensaio de durabilidade'],
  '{"modulo_fineness": "2.0-3.5", "resistencia_esmagamento": "LA30"}',
  ARRAY['EN 206', 'EN 12350'],
  NULL,
  'Norma para agregados para betão',
  ARRAY['agregados', 'betão', 'granulometria'],
  'ALTA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),

-- Normas de Segurança em Obras
(
  gen_random_uuid(),
  'EN 12811-1',
  'Equipamentos de trabalho temporário - Parte 1: Andaimes - Requisitos de execução e estruturas de cálculo',
  'Norma para andaimes',
  'SEGURANCA_OBRAS',
  'Equipamentos de Trabalho',
  'CEN',
  '2003',
  '2003-12-01',
  '2004-06-01',
  'ATIVA',
  'Andaimes',
  ARRAY['Construção', 'Manutenção', 'Reabilitação'],
  ARRAY['Estabilidade', 'Resistência', 'Segurança'],
  ARRAY['Ensaio de carga', 'Ensaio de estabilidade', 'Inspeção visual'],
  '{"carga_maxima": "2.0kN/m²", "altura_maxima": "60m"}',
  ARRAY['EN 12811-2', 'EN 12811-3'],
  NULL,
  'Norma para andaimes',
  ARRAY['andaimes', 'segurança', 'trabalho'],
  'ALTA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'EN 795',
  'Proteção contra quedas - Dispositivos de ancoragem',
  'Norma para dispositivos de ancoragem',
  'SEGURANCA_OBRAS',
  'Proteção Individual',
  'CEN',
  '2012',
  '2012-06-01',
  '2012-12-01',
  'ATIVA',
  'Dispositivos de ancoragem',
  ARRAY['Trabalho em altura', 'Construção', 'Manutenção'],
  ARRAY['Resistência', 'Estabilidade', 'Instalação'],
  ARRAY['Ensaio de resistência', 'Ensaio de estabilidade', 'Ensaio de instalação'],
  '{"carga_maxima": "10kN", "altura_maxima": "100m"}',
  ARRAY['EN 353', 'EN 360'],
  NULL,
  'Norma para dispositivos de ancoragem',
  ARRAY['ancoragem', 'segurança', 'queda'],
  'CRITICA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),

-- Normas de Qualidade e Gestão
(
  gen_random_uuid(),
  'EN ISO 9001',
  'Sistemas de gestão da qualidade - Requisitos',
  'Norma para sistemas de gestão da qualidade',
  'QUALIDADE_GESTAO',
  'Sistemas de Gestão',
  'ISO',
  '2015',
  '2015-09-01',
  '2015-12-01',
  'ATIVA',
  'Sistemas de gestão da qualidade',
  ARRAY['Organizações', 'Processos', 'Produtos'],
  ARRAY['Política da qualidade', 'Objetivos', 'Melhoria contínua'],
  ARRAY['Auditoria', 'Revisão da gestão', 'Análise de dados'],
  '{"ciclo_auditoria": "12meses", "revisao_gestao": "6meses"}',
  ARRAY['EN ISO 14001', 'EN ISO 45001'],
  NULL,
  'Norma fundamental para gestão da qualidade',
  ARRAY['qualidade', 'gestão', 'sistema'],
  'CRITICA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'EN ISO 14001',
  'Sistemas de gestão ambiental - Requisitos com orientação para utilização',
  'Norma para sistemas de gestão ambiental',
  'QUALIDADE_GESTAO',
  'Gestão Ambiental',
  'ISO',
  '2015',
  '2015-09-01',
  '2015-12-01',
  'ATIVA',
  'Sistemas de gestão ambiental',
  ARRAY['Organizações', 'Processos', 'Impacto ambiental'],
  ARRAY['Política ambiental', 'Objetivos', 'Melhoria contínua'],
  ARRAY['Avaliação de impacto', 'Monitorização', 'Auditoria'],
  '{"ciclo_auditoria": "12meses", "revisao_gestao": "6meses"}',
  ARRAY['EN ISO 9001', 'EN ISO 45001'],
  NULL,
  'Norma para gestão ambiental',
  ARRAY['ambiental', 'gestão', 'sistema'],
  'ALTA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),

-- Normas de Ambiente e Sustentabilidade
(
  gen_random_uuid(),
  'EN 15804',
  'Sustentabilidade da construção - Regras de declaração ambiental de produtos',
  'Norma para declaração ambiental de produtos',
  'AMBIENTE_SUSTENTABILIDADE',
  'Avaliação Ambiental',
  'CEN',
  '2012',
  '2012-04-01',
  '2012-10-01',
  'ATIVA',
  'Declaração ambiental de produtos',
  ARRAY['Produtos de construção', 'Materiais', 'Sustentabilidade'],
  ARRAY['Avaliação do ciclo de vida', 'Impacto ambiental', 'Declaração'],
  ARRAY['Análise do ciclo de vida', 'Avaliação de impacto', 'Verificação'],
  '{"periodo_analise": "100anos", "unidade_funcional": "1m²"}',
  ARRAY['EN 15978', 'EN 16309'],
  NULL,
  'Norma para declaração ambiental de produtos',
  ARRAY['ambiental', 'sustentabilidade', 'produtos'],
  'MEDIA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'EN 15978',
  'Sustentabilidade da construção - Avaliação do desempenho ambiental de edifícios',
  'Norma para avaliação ambiental de edifícios',
  'AMBIENTE_SUSTENTABILIDADE',
  'Avaliação de Edifícios',
  'CEN',
  '2011',
  '2011-12-01',
  '2012-06-01',
  'ATIVA',
  'Avaliação ambiental de edifícios',
  ARRAY['Edifícios', 'Construção', 'Sustentabilidade'],
  ARRAY['Avaliação do ciclo de vida', 'Impacto ambiental', 'Desempenho'],
  ARRAY['Análise do ciclo de vida', 'Avaliação de impacto', 'Simulação'],
  '{"periodo_analise": "50anos", "unidade_funcional": "1m²"}',
  ARRAY['EN 15804', 'EN 16309'],
  NULL,
  'Norma para avaliação ambiental de edifícios',
  ARRAY['ambiental', 'edifícios', 'sustentabilidade'],
  'MEDIA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),

-- Normas de Acessibilidade
(
  gen_random_uuid(),
  'EN 81-70',
  'Regras de segurança para a construção e instalação de elevadores - Acessibilidade a elevadores para pessoas incluindo pessoas com deficiência',
  'Norma para acessibilidade de elevadores',
  'ACESSIBILIDADE',
  'Elevadores',
  'CEN',
  '2018',
  '2018-06-01',
  '2018-12-01',
  'ATIVA',
  'Acessibilidade de elevadores',
  ARRAY['Elevadores', 'Acessibilidade', 'Deficiência'],
  ARRAY['Dimensões', 'Comandos', 'Sinalização'],
  ARRAY['Medição de dimensões', 'Teste de comandos', 'Verificação de sinalização'],
  '{"largura_minima": "1100mm", "profundidade_minima": "1400mm"}',
  ARRAY['EN 81-1', 'EN 81-2'],
  NULL,
  'Norma para acessibilidade de elevadores',
  ARRAY['acessibilidade', 'elevadores', 'deficiência'],
  'ALTA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'EN 17210',
  'Acessibilidade e usabilidade do ambiente construído - Requisitos funcionais',
  'Norma para acessibilidade do ambiente construído',
  'ACESSIBILIDADE',
  'Ambiente Construído',
  'CEN',
  '2021',
  '2021-03-01',
  '2021-09-01',
  'ATIVA',
  'Acessibilidade do ambiente construído',
  ARRAY['Edifícios', 'Espaços públicos', 'Infraestruturas'],
  ARRAY['Acessibilidade', 'Usabilidade', 'Inclusão'],
  ARRAY['Avaliação de acessibilidade', 'Teste de usabilidade', 'Verificação de inclusão'],
  '{"rampa_maxima": "8%", "corrimao_altura": "900mm"}',
  ARRAY['EN 17210-1', 'EN 17210-2'],
  NULL,
  'Norma para acessibilidade do ambiente construído',
  ARRAY['acessibilidade', 'ambiente', 'inclusão'],
  'ALTA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),

-- Normas de Energia e Eficiência
(
  gen_random_uuid(),
  'EN 15251',
  'Critérios do ambiente interior para concepção e avaliação do desempenho energético de edifícios',
  'Norma para critérios do ambiente interior',
  'ENERGIA_EFICIENCIA',
  'Ambiente Interior',
  'CEN',
  '2007',
  '2007-12-01',
  '2008-06-01',
  'ATIVA',
  'Critérios do ambiente interior',
  ARRAY['Edifícios', 'Conforto', 'Energia'],
  ARRAY['Temperatura', 'Humidade', 'Qualidade do ar'],
  ARRAY['Medição de temperatura', 'Medição de humidade', 'Medição de qualidade do ar'],
  '{"temperatura_minima": "20°C", "temperatura_maxima": "26°C"}',
  ARRAY['EN 13779', 'EN 15232'],
  NULL,
  'Norma para critérios do ambiente interior',
  ARRAY['ambiente', 'conforto', 'energia'],
  'MEDIA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'EN 15232',
  'Desempenho energético de edifícios - Impacto da automação, controlo e gestão técnica de edifícios',
  'Norma para automação e controlo de edifícios',
  'ENERGIA_EFICIENCIA',
  'Automação de Edifícios',
  'CEN',
  '2012',
  '2012-06-01',
  '2012-12-01',
  'ATIVA',
  'Automação e controlo de edifícios',
  ARRAY['Edifícios', 'Automação', 'Energia'],
  ARRAY['Controlo', 'Gestão', 'Eficiência'],
  ARRAY['Teste de controlo', 'Teste de gestão', 'Avaliação de eficiência'],
  '{"eficiencia_minima": "15%", "controlo_temperatura": "±1°C"}',
  ARRAY['EN 15251', 'EN 13779'],
  NULL,
  'Norma para automação e controlo de edifícios',
  ARRAY['automação', 'controlo', 'energia'],
  'MEDIA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),

-- Normas de Sinalização e Segurança
(
  gen_random_uuid(),
  'EN 12899-1',
  'Postes fixos, verticais, de sinalização rodoviária - Parte 1: Postes fixos, verticais, de sinalização rodoviária',
  'Norma para postes de sinalização',
  'SINALIZACAO_SEGURANCA',
  'Sinalização Rodoviária',
  'CEN',
  '2007',
  '2007-12-01',
  '2008-06-01',
  'ATIVA',
  'Postes de sinalização rodoviária',
  ARRAY['Sinalização', 'Rodovias', 'Segurança'],
  ARRAY['Resistência', 'Estabilidade', 'Visibilidade'],
  ARRAY['Ensaio de resistência', 'Ensaio de estabilidade', 'Ensaio de visibilidade'],
  '{"altura_minima": "2.5m", "resistencia_vento": "150km/h"}',
  ARRAY['EN 12899-2', 'EN 12899-3'],
  NULL,
  'Norma para postes de sinalização rodoviária',
  ARRAY['sinalização', 'rodoviária', 'postes'],
  'ALTA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'EN 60529',
  'Graus de proteção fornecidos por invólucros (Código IP)',
  'Norma para graus de proteção IP',
  'SINALIZACAO_SEGURANCA',
  'Proteção de Equipamentos',
  'CENELEC',
  '1991',
  '1991-12-01',
  '1992-06-01',
  'ATIVA',
  'Graus de proteção IP',
  ARRAY['Equipamentos', 'Proteção', 'Segurança'],
  ARRAY['Proteção contra poeiras', 'Proteção contra água', 'Proteção contra impactos'],
  ARRAY['Ensaio de proteção contra poeiras', 'Ensaio de proteção contra água', 'Ensaio de proteção contra impactos'],
  '{"protecao_poeiras": "IP5X", "protecao_agua": "IPX4"}',
  ARRAY['EN 60068', 'EN 60598'],
  NULL,
  'Norma para graus de proteção IP',
  ARRAY['proteção', 'IP', 'equipamentos'],
  'MEDIA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),

-- Normas de Manutenção e Operação
(
  gen_random_uuid(),
  'EN 13306',
  'Manutenção - Terminologia da manutenção',
  'Norma para terminologia da manutenção',
  'MANUTENCAO_OPERACAO',
  'Terminologia',
  'CEN',
  '2018',
  '2018-03-01',
  '2018-09-01',
  'ATIVA',
  'Terminologia da manutenção',
  ARRAY['Manutenção', 'Operação', 'Gestão'],
  ARRAY['Definições', 'Termos', 'Conceitos'],
  ARRAY['Documentação', 'Comunicação', 'Formação'],
  '{"ciclo_manutencao": "12meses", "tempo_resposta": "24h"}',
  ARRAY['EN 15341', 'EN 17007'],
  NULL,
  'Norma para terminologia da manutenção',
  ARRAY['manutenção', 'terminologia', 'gestão'],
  'MEDIA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'EN 15341',
  'Indicadores de manutenção',
  'Norma para indicadores de manutenção',
  'MANUTENCAO_OPERACAO',
  'Indicadores',
  'CEN',
  '2019',
  '2019-06-01',
  '2019-12-01',
  'ATIVA',
  'Indicadores de manutenção',
  ARRAY['Manutenção', 'Gestão', 'Análise'],
  ARRAY['Indicadores', 'Métricas', 'Desempenho'],
  ARRAY['Cálculo de indicadores', 'Análise de métricas', 'Avaliação de desempenho'],
  '{"disponibilidade_minima": "95%", "eficiencia_manutencao": "85%"}',
  ARRAY['EN 13306', 'EN 17007'],
  NULL,
  'Norma para indicadores de manutenção',
  ARRAY['manutenção', 'indicadores', 'desempenho'],
  'MEDIA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),

-- Normas de Inspeção e Controlo
(
  gen_random_uuid(),
  'EN 473',
  'Qualificação e certificação de pessoal de ensaio não destrutivo - Princípios gerais',
  'Norma para qualificação de pessoal de END',
  'INSPECAO_CONTROLO',
  'Qualificação de Pessoal',
  'CEN',
  '2008',
  '2008-12-01',
  '2009-06-01',
  'ATIVA',
  'Qualificação de pessoal de END',
  ARRAY['Ensaios não destrutivos', 'Qualificação', 'Certificação'],
  ARRAY['Formação', 'Exame', 'Certificação'],
  ARRAY['Exame teórico', 'Exame prático', 'Avaliação de competências'],
  '{"formacao_minima": "40h", "experiencia_minima": "12meses"}',
  ARRAY['EN 9712', 'EN 12062'],
  NULL,
  'Norma para qualificação de pessoal de END',
  ARRAY['END', 'qualificação', 'certificação'],
  'ALTA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'EN 12062',
  'Ensaios não destrutivos de soldaduras - Métodos gerais para todos os tipos de materiais',
  'Norma para ensaios não destrutivos de soldaduras',
  'INSPECAO_CONTROLO',
  'Ensaios Não Destrutivos',
  'CEN',
  '2018',
  '2018-06-01',
  '2018-12-01',
  'ATIVA',
  'Ensaios não destrutivos de soldaduras',
  ARRAY['Soldaduras', 'Inspeção', 'Controlo'],
  ARRAY['Qualidade', 'Defeitos', 'Aceitação'],
  ARRAY['Inspeção visual', 'Ensaio por partículas magnéticas', 'Ensaio por líquidos penetrantes'],
  '{"sensibilidade_minima": "2mm", "cobertura_100%": true}',
  ARRAY['EN 473', 'EN 9712'],
  NULL,
  'Norma para ensaios não destrutivos de soldaduras',
  ARRAY['END', 'soldaduras', 'inspeção'],
  'ALTA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),

-- Normas de Documentação Técnica
(
  gen_random_uuid(),
  'EN ISO 7200',
  'Documentação técnica de produtos - Dados em campos de título e cabeçalhos de documentos',
  'Norma para documentação técnica',
  'DOCUMENTACAO_TECNICA',
  'Documentação de Produtos',
  'ISO',
  '2004',
  '2004-12-01',
  '2005-06-01',
  'ATIVA',
  'Documentação técnica de produtos',
  ARRAY['Produtos', 'Documentação', 'Informação'],
  ARRAY['Estrutura', 'Conteúdo', 'Formato'],
  ARRAY['Revisão de documentação', 'Verificação de conteúdo', 'Avaliação de formato'],
  '{"campos_obrigatorios": "10", "formato_padrao": "A4"}',
  ARRAY['EN ISO 5457', 'EN ISO 3098'],
  NULL,
  'Norma para documentação técnica de produtos',
  ARRAY['documentação', 'técnica', 'produtos'],
  'MEDIA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
),
(
  gen_random_uuid(),
  'EN ISO 5457',
  'Desenho técnico - Formatos e elementos de apresentação',
  'Norma para formatos de desenho técnico',
  'DOCUMENTACAO_TECNICA',
  'Desenho Técnico',
  'ISO',
  '1999',
  '1999-12-01',
  '2000-06-01',
  'ATIVA',
  'Formatos de desenho técnico',
  ARRAY['Desenho técnico', 'Formato', 'Apresentação'],
  ARRAY['Dimensões', 'Margens', 'Escala'],
  ARRAY['Verificação de formato', 'Verificação de margens', 'Verificação de escala'],
  '{"formato_padrao": "A4", "margem_minima": "10mm"}',
  ARRAY['EN ISO 7200', 'EN ISO 3098'],
  NULL,
  'Norma para formatos de desenho técnico',
  ARRAY['desenho', 'técnico', 'formato'],
  'MEDIA',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z',
  '2024-01-15T10:00:00Z'
);

-- Reabilitar RLS
ALTER TABLE normas ENABLE ROW LEVEL SECURITY;

-- Verificar dados inseridos
SELECT 
  codigo,
  titulo,
  categoria,
  organismo,
  status,
  prioridade,
  data_publicacao
FROM normas 
ORDER BY categoria, codigo;

-- Estatísticas por categoria
SELECT 
  categoria,
  COUNT(*) as total_normas,
  COUNT(CASE WHEN status = 'ATIVA' THEN 1 END) as normas_ativas,
  COUNT(CASE WHEN prioridade = 'CRITICA' THEN 1 END) as normas_criticas
FROM normas 
GROUP BY categoria 
ORDER BY total_normas DESC;
