-- Script para adicionar dados mock à tabela submissoes_materiais
-- Desabilitar RLS temporariamente
ALTER TABLE submissoes_materiais DISABLE ROW LEVEL SECURITY;

-- Inserir dados mock
INSERT INTO submissoes_materiais (
  codigo,
  titulo,
  descricao,
  tipo_material,
  categoria,
  especificacoes_tecnicas,
  normas_referencia,
  certificados_necessarios,
  submissor_id,
  submissor_nome,
  data_submissao,
  prioridade,
  urgencia,
  estado,
  especificacoes_detalhadas,
  justificativa_necessidade,
  impacto_custo,
  impacto_prazo,
  obra_id,
  obra_nome,
  fornecedor_sugerido,
  fornecedor_alternativo,
  tags,
  observacoes,
  data_limite_aprovacao,
  documentos_anexos,
  etapa_atual,
  historico_aprovacoes,
  comentarios
) VALUES 
-- Submissão 1: Betão estrutural
(
  'SM-2024-001',
  'Betão C25/30 para Pilares',
  'Submissão de betão estrutural classe C25/30 para pilares da ponte',
  'betao',
  'estrutural',
  'Classe C25/30, consistência S3, agregado máximo 20mm',
  ARRAY['EN 206-1', 'NP EN 206-1'],
  ARRAY['Certificado de conformidade', 'Ficha técnica'],
  'user-001',
  'Eng. João Silva',
  '2024-01-15',
  'alta',
  'normal',
  'aprovado',
  'Betão estrutural com resistência característica à compressão de 25 MPa aos 28 dias. Consistência S3 para facilitar a aplicação em pilares.',
  'Necessário para garantir a resistência estrutural dos pilares da ponte principal',
  15000.00,
  5,
  'obra-001',
  'Ponte do Rio Douro',
  'Cimpor',
  'Secil',
  ARRAY['estrutural', 'ponte', 'pilares'],
  'Aprovação condicionada à apresentação de ensaios de resistência',
  '2024-02-15',
  '[]',
  'aprovado',
  '[]',
  '[]'
),

-- Submissão 2: Aço para armaduras
(
  'SM-2024-002',
  'Aço B500B para Armaduras',
  'Submissão de aço B500B para armaduras das lajes',
  'aco',
  'armaduras',
  'Aço B500B, diâmetros 8, 10, 12, 16mm',
  ARRAY['EN 10080', 'NP EN 10080'],
  ARRAY['Certificado de conformidade', 'Ensaio de tração'],
  'user-002',
  'Eng. Maria Santos',
  '2024-01-20',
  'media',
  'urgente',
  'em_revisao',
  'Aço para armaduras com limite de escoamento de 500 MPa. Diâmetros disponíveis: 8, 10, 12, 16mm.',
  'Necessário para as armaduras das lajes do viaduto',
  25000.00,
  3,
  'obra-002',
  'Viaduto da A1',
  'Megasa',
  'Celsa',
  ARRAY['armaduras', 'lajes', 'viaduto'],
  'Em análise técnica',
  '2024-02-20',
  '[]',
  'em_revisao',
  '[]',
  '[]'
),

-- Submissão 3: Geotêxtil
(
  'SM-2024-003',
  'Geotêxtil para Drenagem',
  'Submissão de geotêxtil para sistema de drenagem',
  'geossinteticos',
  'drenagem',
  'Geotêxtil não tecido, massa 200g/m²',
  ARRAY['EN ISO 10320', 'NP EN ISO 10320'],
  ARRAY['Certificado de conformidade', 'Ensaio de resistência'],
  'user-003',
  'Eng. Pedro Costa',
  '2024-01-25',
  'baixa',
  'normal',
  'submetido',
  'Geotêxtil não tecido para drenagem com massa de 200g/m². Resistência à tração mínima de 8 kN/m.',
  'Necessário para o sistema de drenagem do aterro',
  8000.00,
  2,
  'obra-003',
  'Aterro da Linha do Norte',
  'Tencate',
  'Huesker',
  ARRAY['drenagem', 'aterro', 'geotêxtil'],
  'Aguardando aprovação',
  '2024-02-25',
  '[]',
  'submetido',
  '[]',
  '[]'
),

-- Submissão 4: Betão pré-fabricado
(
  'SM-2024-004',
  'Vigas Pré-fabricadas',
  'Submissão de vigas pré-fabricadas para viaduto',
  'pre_fabricado',
  'estrutural',
  'Vigas pré-fabricadas de betão C35/45, vão 30m',
  ARRAY['EN 13369', 'NP EN 13369'],
  ARRAY['Certificado de conformidade', 'Ensaio de carga'],
  'user-004',
  'Eng. Ana Ferreira',
  '2024-02-01',
  'critica',
  'muito_urgente',
  'aguardando_aprovacao',
  'Vigas pré-fabricadas de betão C35/45 com vão de 30m. Altura 1.5m, largura 0.8m.',
  'Crítico para o cronograma da obra. Prazo de fabricação de 8 semanas',
  120000.00,
  15,
  'obra-004',
  'Viaduto da A4',
  'Prebetão',
  'Precon',
  ARRAY['pre-fabricado', 'vigas', 'viaduto'],
  'Aprovação urgente necessária',
  '2024-03-01',
  '[]',
  'aguardando_aprovacao',
  '[]',
  '[]'
),

-- Submissão 5: Material de vedação
(
  'SM-2024-005',
  'Juntas de Dilatação',
  'Submissão de juntas de dilatação para pontes',
  'vedacao',
  'juntas',
  'Juntas de dilatação tipo finger, 200mm de abertura',
  ARRAY['EN 1337-3', 'NP EN 1337-3'],
  ARRAY['Certificado de conformidade', 'Ensaio de durabilidade'],
  'user-005',
  'Eng. Carlos Lima',
  '2024-02-05',
  'media',
  'normal',
  'rejeitado',
  'Juntas de dilatação tipo finger com abertura de 200mm. Material: aço inoxidável.',
  'Necessário para as juntas de dilatação das pontes',
  18000.00,
  4,
  'obra-005',
  'Ponte da A25',
  'Mageba',
  'DS Brown',
  ARRAY['juntas', 'dilatação', 'pontes'],
  'Rejeitado - especificações não adequadas',
  '2024-03-05',
  '[]',
  'rejeitado',
  '[]',
  '[]'
),

-- Submissão 6: Material de impermeabilização
(
  'SM-2024-006',
  'Membrana de Impermeabilização',
  'Submissão de membrana para impermeabilização de túneis',
  'impermeabilizacao',
  'membranas',
  'Membrana PVC, espessura 2mm, resistência química',
  ARRAY['EN 13967', 'NP EN 13967'],
  ARRAY['Certificado de conformidade', 'Ensaio de resistência química'],
  'user-006',
  'Eng. Sofia Martins',
  '2024-02-10',
  'alta',
  'urgente',
  'solicitado_alteracao',
  'Membrana de PVC com espessura de 2mm. Resistência química para ambiente de túnel.',
  'Necessário para a impermeabilização dos túneis',
  35000.00,
  7,
  'obra-006',
  'Túnel do Marão',
  'Sika',
  'BASF',
  ARRAY['impermeabilização', 'túnel', 'membrana'],
  'Solicitadas alterações nas especificações',
  '2024-03-10',
  '[]',
  'solicitado_alteracao',
  '[]',
  '[]'
),

-- Submissão 7: Material de sinalização
(
  'SM-2024-007',
  'Painéis de Sinalização',
  'Submissão de painéis de sinalização ferroviária',
  'sinalizacao',
  'painels',
  'Painéis retro-refletivos, classe R2',
  ARRAY['EN 12899-1', 'NP EN 12899-1'],
  ARRAY['Certificado de conformidade', 'Ensaio de retro-reflexão'],
  'user-007',
  'Eng. Ricardo Alves',
  '2024-02-15',
  'baixa',
  'normal',
  'aprovado',
  'Painéis de sinalização retro-refletivos classe R2. Material: alumínio com película retro-refletiva.',
  'Necessário para a sinalização da linha ferroviária',
  12000.00,
  3,
  'obra-007',
  'Linha do Minho',
  '3M',
  'Avery Dennison',
  ARRAY['sinalização', 'ferroviária', 'painéis'],
  'Aprovado com sucesso',
  '2024-03-15',
  '[]',
  'aprovado',
  '[]',
  '[]'
),

-- Submissão 8: Material de fundação
(
  'SM-2024-008',
  'Estacas Metálicas',
  'Submissão de estacas metálicas para fundações',
  'fundacoes',
  'estacas',
  'Estacas metálicas HEB 300, comprimento 15m',
  ARRAY['EN 10210', 'NP EN 10210'],
  ARRAY['Certificado de conformidade', 'Ensaio de resistência'],
  'user-008',
  'Eng. Luísa Pereira',
  '2024-02-20',
  'critica',
  'muito_urgente',
  'em_revisao',
  'Estacas metálicas perfil HEB 300 com comprimento de 15m. Aço S355.',
  'Crítico para as fundações da ponte. Prazo de fornecimento de 6 semanas',
  85000.00,
  12,
  'obra-008',
  'Ponte do Guadiana',
  'ArcelorMittal',
  'Tata Steel',
  ARRAY['fundações', 'estacas', 'ponte'],
  'Em análise técnica urgente',
  '2024-03-20',
  '[]',
  'em_revisao',
  '[]',
  '[]'
),

-- Submissão 9: Material de acabamento
(
  'SM-2024-009',
  'Pavimento Betuminoso',
  'Submissão de pavimento betuminoso para plataforma',
  'pavimentos',
  'betuminoso',
  'Mistura betuminosa AC20 surf, espessura 5cm',
  ARRAY['EN 13108-1', 'NP EN 13108-1'],
  ARRAY['Certificado de conformidade', 'Ensaio de Marshall'],
  'user-009',
  'Eng. Manuel Santos',
  '2024-02-25',
  'media',
  'normal',
  'submetido',
  'Mistura betuminosa AC20 surf com espessura de 5cm. Agregado máximo 20mm.',
  'Necessário para o pavimento da plataforma ferroviária',
  28000.00,
  5,
  'obra-009',
  'Estação de Braga',
  'Repsol',
  'Galp',
  ARRAY['pavimento', 'betuminoso', 'plataforma'],
  'Aguardando aprovação',
  '2024-03-25',
  '[]',
  'submetido',
  '[]',
  '[]'
),

-- Submissão 10: Material de segurança
(
  'SM-2024-010',
  'Barreiras de Segurança',
  'Submissão de barreiras de segurança para viaduto',
  'seguranca',
  'barreiras',
  'Barreiras metálicas H2, altura 0.8m',
  ARRAY['EN 1317-2', 'NP EN 1317-2'],
  ARRAY['Certificado de conformidade', 'Ensaio de impacto'],
  'user-010',
  'Eng. Teresa Oliveira',
  '2024-03-01',
  'alta',
  'urgente',
  'aprovado',
  'Barreiras de segurança metálicas classe H2 com altura de 0.8m. Material: aço galvanizado.',
  'Necessário para a segurança do viaduto',
  22000.00,
  6,
  'obra-010',
  'Viaduto da A3',
  'Guardrail',
  'Armco',
  ARRAY['segurança', 'barreiras', 'viaduto'],
  'Aprovado com sucesso',
  '2024-04-01',
  '[]',
  'aprovado',
  '[]',
  '[]'
);

-- Reabilitar RLS
ALTER TABLE submissoes_materiais ENABLE ROW LEVEL SECURITY;

-- Verificar dados inseridos
SELECT 
  codigo,
  titulo,
  tipo_material,
  categoria,
  estado,
  prioridade,
  submissor_nome,
  data_submissao
FROM submissoes_materiais 
ORDER BY data_submissao DESC;

-- Estatísticas
SELECT 
  COUNT(*) as total_submissoes,
  COUNT(CASE WHEN estado = 'aprovado' THEN 1 END) as aprovadas,
  COUNT(CASE WHEN estado IN ('submetido', 'em_revisao', 'aguardando_aprovacao') THEN 1 END) as pendentes,
  COUNT(CASE WHEN estado = 'rejeitado' THEN 1 END) as rejeitadas,
  COUNT(CASE WHEN urgencia IN ('urgente', 'muito_urgente') THEN 1 END) as urgentes,
  COUNT(CASE WHEN prioridade = 'critica' THEN 1 END) as criticas
FROM submissoes_materiais;
